version: '3'

services:
    db:
        image: mysql
        #A mettre sur OSX et windows sinon permission denied
        user: "1000:50"
        restart: always
        volumes:
          - ./mysql-datadir:/var/lib/mysql
        ports:
          - 6603:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

    front:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
          - ./front/www:/var/www/html
          #- ./front/code:/code
          #- ./front/conf/site.conf:/etc/nginx/conf.d/000_site.conf
          - ./front/conf/site.conf:/etc/nginx/conf.d/default.conf
          #- ./front/config:/etc/nginx
          - ./front/logs:/var/log/nginx
          #- ./front/data:/home/http

  #ou faire un data/nginx, data/mysql, ... conf/nginx, conf/php,...  log/nginx log/
  #https://github.com/EtreRe/docker-compose-baseimage/blob/master/docker-compose.yml
        links:
          - php
    php:
      image: php:7-fpm
      volumes:
        - ./front/www:/var/www/html
        # prefix zz to load the config last, so that's not overriden by the rest of the config
        - ./engine/conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf