version: '2'

services:
    db:
        image: mysql
        #A mettre sur OSX et windows sinon permission denied
        user: "1000:50"
        restart: always
        volumes:
          - ./data/mysql:/var/lib/mysql
        ports:
          - 6603:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

    front:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
          - ./data/www:/var/www/html
          - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
          - ./logs/nginx:/var/log/nginx
        links:
          - php
    php:
      image: php:7-fpm
      volumes:
        - ./data/www:/var/www/html
        # prefix zz to load the config last, so that's not overriden by the rest of the config
        - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz_log.conf